version: "3.8"

services:
  mongo_configs_db:
    container_name: mongo_configs_db
    image: ghcr.io/joseesco24/mongo_configs_db:latest
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - dockerized_databases_network
    ports:
      - target: 27017
        published: 5440
        protocol: tcp
    volumes:
      - type: volume
        source: mongo_configs_db_disc
        target: /data/db

networks:
  dockerized_databases_network:
    name: dockerized_databases_network
    external: false
    driver: bridge

volumes:
  mongo_configs_db_disc:
